service: invitation-service

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2

functions:
  test:
    handler: src/test.handler
    events:
      - httpApi:
          path: /test
          method: get
          cors: true
